import "inspectable.idl";
import "windows.foundation.idl";
import "windows.system.remotesystems.idl";

namespace Windows.ApplicationModel.Internal.DataTransfer.NearShare{

    [version(1.0)]
    enum NearShareStatus {
        Unknown = 0,
        Completed = 1,
        InProgress = 2,
        TimedOut = 3,
        DeniedByRemoteSystem = 5,
        VersionMismatch = 6,
        ConnectionEstablished = 7,
        NoSignedInUser = 8,
        NetworkError = 9,
        PlatformError = 10
    };

    [version(1.0)]
    struct SendDataProgress {
        NearShareStatus Status;
        UInt64 TotalBytes;
        UInt64 SentBytes;
        UInt32 TotalFiles;
        UInt32 SentFiles;
    };

    runtimeclass ShareSenderBroker;

    [version(1.0)]
    [uuid(1a975b05-870a-4e8f-b910-f0986d481bab)]
    interface ICDPComNearShareSender : IInspectable
    {
    };

    [version(1.0)]
    [exclusiveto(ShareSenderBroker)]
    [uuid(898d173c-121d-42a1-835c-0f315e380402)]
    interface IShareSenderBroker : IInspectable
    {
        HRESULT ShareDataWithProgressAsync(
            [in] HSTRING correlationVector,
            [in] Windows.System.RemoteSystems.RemoteSystem* receiver,
            [in] Windows.ApplicationModel.DataTransfer.DataPackage* data,
            [in] HSTRING dataType,
            [out, retval] Windows.Foundation.IAsyncOperationWithProgress<NearShareStatus, SendDataProgress>** progress
        );
    };

    [version(1.0)]
    [activatable(1.0)]
    runtimeclass ShareSenderBroker
    {
        [default] interface IShareSenderBroker;
    };

    // UniformResourceLocatorW
    // Shell IDList Array
}
